<?php

$html = [
'<div class="field left" style="top:1.10in;left:4.43in;width:1.24in;height:0.19in;"><div class="data-left">'.'Podatak'.'</div></div>'.
'<div class="field left" style="top:1.10in;left:6.28in;width:1.59in;height:0.19in;"><div class="data-left">'.'Podatak'.'</div></div>'.
'<div class="field left" style="top:1.38in;left:2.36in;width:3.31in;height:0.19in;"><div class="data-left">'.'Podatak'.'</div></div>'.
'<div class="field left" style="top:1.38in;left:6.28in;width:1.59in;height:0.19in;"><div class="data-left">'.'Podatak'.'</div></div>'.
'<div class="field left" style="top:3.06in;left:1.57in;width:4.82in;height:0.24in;"><div class="data-left">'.'Podatak'.'</div></div>'.
'<div class="field right" style="top:3.07in;left:6.55in;width:1.29in;height:0.20in;"><div class="data-right">'.'numero'.'</div></div>'.
'<div class="field date" style="top:3.13in;left:0.61in;width:0.08in;height:0.08in;"><div class="data-left">'.'123'.'</div></div>'.
'<div class="field date" style="top:3.13in;left:1.20in;width:0.08in;height:0.08in;"><div class="data-left">'.'123'.'</div></div>'.
'<div class="field left" style="top:3.31in;left:1.57in;width:4.82in;height:0.24in;"><div class="data-left">'.'Podatak'.'</div></div>'.
'<div class="field right" style="top:3.32in;left:6.55in;width:1.29in;height:0.20in;"><div class="data-right">'.'numero'.'</div></div>'.
'<div class="field date" style="top:3.38in;left:0.61in;width:0.08in;height:0.08in;"><div class="data-left">'.'123'.'</div></div>'.
'<div class="field date" style="top:3.38in;left:1.20in;width:0.08in;height:0.08in;"><div class="data-left">'.'123'.'</div></div>'.
'<div class="field left" style="top:3.56in;left:1.57in;width:4.82in;height:0.24in;"><div class="data-left">'.'Podatak'.'</div></div>'.
'<div class="field right" style="top:3.57in;left:6.55in;width:1.29in;height:0.20in;"><div class="data-right">'.'numero'.'</div></div>'.
'<div class="field date" style="top:3.63in;left:0.61in;width:0.08in;height:0.08in;"><div class="data-left">'.'123'.'</div></div>'.
'<div class="field date" style="top:3.63in;left:1.20in;width:0.08in;height:0.08in;"><div class="data-left">'.'123'.'</div></div>'.
'<div class="field left" style="top:3.81in;left:1.57in;width:4.82in;height:0.24in;"><div class="data-left">'.'Podatak'.'</div></div>'.
'<div class="field right" style="top:3.82in;left:6.55in;width:1.29in;height:0.20in;"><div class="data-right">'.'numero'.'</div></div>'.
'<div class="field date" style="top:3.88in;left:0.61in;width:0.08in;height:0.08in;"><div class="data-left">'.'123'.'</div></div>'.
'<div class="field date" style="top:3.88in;left:1.20in;width:0.08in;height:0.08in;"><div class="data-left">'.'123'.'</div></div>'.
'<div class="field left" style="top:4.06in;left:1.57in;width:4.82in;height:0.24in;"><div class="data-left">'.'Podatak'.'</div></div>'.
'<div class="field right" style="top:4.07in;left:6.55in;width:1.29in;height:0.20in;"><div class="data-right">'.'numero'.'</div></div>'.
'<div class="field date" style="top:4.13in;left:0.61in;width:0.08in;height:0.08in;"><div class="data-left">'.'123'.'</div></div>'.
'<div class="field date" style="top:4.13in;left:1.20in;width:0.08in;height:0.08in;"><div class="data-left">'.'123'.'</div></div>'.
'<div class="field left" style="top:4.31in;left:1.57in;width:4.82in;height:0.24in;"><div class="data-left">'.'Podatak'.'</div></div>'.
'<div class="field right" style="top:4.32in;left:6.55in;width:1.29in;height:0.20in;"><div class="data-right">'.'numero'.'</div></div>'.
'<div class="field date" style="top:4.38in;left:0.61in;width:0.08in;height:0.08in;"><div class="data-left">'.'123'.'</div></div>'.
'<div class="field date" style="top:4.38in;left:1.20in;width:0.08in;height:0.08in;"><div class="data-left">'.'123'.'</div></div>'.
'<div class="field left" style="top:4.56in;left:1.57in;width:4.82in;height:0.24in;"><div class="data-left">'.'Podatak'.'</div></div>'.
'<div class="field right" style="top:4.57in;left:6.55in;width:1.29in;height:0.20in;"><div class="data-right">'.'numero'.'</div></div>'.
'<div class="field date" style="top:4.63in;left:0.61in;width:0.08in;height:0.08in;"><div class="data-left">'.'123'.'</div></div>'.
'<div class="field date" style="top:4.63in;left:1.20in;width:0.08in;height:0.08in;"><div class="data-left">'.'123'.'</div></div>'.
'<div class="field left" style="top:4.81in;left:1.57in;width:4.82in;height:0.24in;"><div class="data-left">'.'Podatak'.'</div></div>'.
'<div class="field right" style="top:4.82in;left:6.55in;width:1.29in;height:0.20in;"><div class="data-right">'.'numero'.'</div></div>'.
'<div class="field date" style="top:4.88in;left:0.61in;width:0.08in;height:0.08in;"><div class="data-left">'.'123'.'</div></div>'.
'<div class="field date" style="top:4.88in;left:1.20in;width:0.08in;height:0.08in;"><div class="data-left">'.'123'.'</div></div>'.
'<div class="field left" style="top:5.06in;left:1.57in;width:4.82in;height:0.24in;"><div class="data-left">'.'Podatak'.'</div></div>'.
'<div class="field right" style="top:5.07in;left:6.55in;width:1.29in;height:0.20in;"><div class="data-right">'.'numero'.'</div></div>'.
'<div class="field date" style="top:5.13in;left:0.61in;width:0.08in;height:0.08in;"><div class="data-left">'.'123'.'</div></div>'.
'<div class="field date" style="top:5.13in;left:1.20in;width:0.08in;height:0.08in;"><div class="data-left">'.'123'.'</div></div>'.
'<div class="field left" style="top:5.31in;left:1.57in;width:4.82in;height:0.24in;"><div class="data-left">'.'Podatak'.'</div></div>'.
'<div class="field right" style="top:5.32in;left:6.55in;width:1.29in;height:0.20in;"><div class="data-right">'.'numero'.'</div></div>'.
'<div class="field date" style="top:5.38in;left:0.61in;width:0.08in;height:0.08in;"><div class="data-left">'.'123'.'</div></div>'.
'<div class="field date" style="top:5.38in;left:1.20in;width:0.08in;height:0.08in;"><div class="data-left">'.'123'.'</div></div>'.
'<div class="field left" style="top:5.56in;left:1.57in;width:4.82in;height:0.24in;"><div class="data-left">'.'Podatak'.'</div></div>'.
'<div class="field right" style="top:5.57in;left:6.55in;width:1.29in;height:0.20in;"><div class="data-right">'.'numero'.'</div></div>'.
'<div class="field date" style="top:5.63in;left:0.61in;width:0.08in;height:0.08in;"><div class="data-left">'.'123'.'</div></div>'.
'<div class="field date" style="top:5.63in;left:1.20in;width:0.08in;height:0.08in;"><div class="data-left">'.'123'.'</div></div>'.
'<div class="field left" style="top:5.81in;left:1.57in;width:4.82in;height:0.24in;"><div class="data-left">'.'Podatak'.'</div></div>'.
'<div class="field right" style="top:5.82in;left:6.55in;width:1.29in;height:0.20in;"><div class="data-right">'.'numero'.'</div></div>'.
'<div class="field date" style="top:5.88in;left:0.61in;width:0.08in;height:0.08in;"><div class="data-left">'.'123'.'</div></div>'.
'<div class="field date" style="top:5.88in;left:1.20in;width:0.08in;height:0.08in;"><div class="data-left">'.'123'.'</div></div>'.
'<div class="field left" style="top:6.06in;left:1.57in;width:4.82in;height:0.24in;"><div class="data-left">'.'Podatak'.'</div></div>'.
'<div class="field right" style="top:6.07in;left:6.55in;width:1.29in;height:0.20in;"><div class="data-right">'.'numero'.'</div></div>'.
'<div class="field date" style="top:6.13in;left:0.61in;width:0.08in;height:0.08in;"><div class="data-left">'.'123'.'</div></div>'.
'<div class="field date" style="top:6.13in;left:1.20in;width:0.08in;height:0.08in;"><div class="data-left">'.'123'.'</div></div>'.
'<div class="field left" style="top:6.31in;left:1.57in;width:4.82in;height:0.24in;"><div class="data-left">'.'Podatak'.'</div></div>'.
'<div class="field right" style="top:6.32in;left:6.55in;width:1.29in;height:0.20in;"><div class="data-right">'.'numero'.'</div></div>'.
'<div class="field date" style="top:6.38in;left:0.61in;width:0.08in;height:0.08in;"><div class="data-left">'.'123'.'</div></div>'.
'<div class="field date" style="top:6.38in;left:1.20in;width:0.08in;height:0.08in;"><div class="data-left">'.'123'.'</div></div>'.
'<div class="field left" style="top:6.56in;left:1.57in;width:4.82in;height:0.24in;"><div class="data-left">'.'Podatak'.'</div></div>'.
'<div class="field right" style="top:6.57in;left:6.55in;width:1.29in;height:0.20in;"><div class="data-right">'.'numero'.'</div></div>'.
'<div class="field date" style="top:6.63in;left:0.61in;width:0.08in;height:0.08in;"><div class="data-left">'.'123'.'</div></div>'.
'<div class="field date" style="top:6.63in;left:1.20in;width:0.08in;height:0.08in;"><div class="data-left">'.'123'.'</div></div>'.
'<div class="field left" style="top:6.81in;left:1.57in;width:4.82in;height:0.24in;"><div class="data-left">'.'Podatak'.'</div></div>'.
'<div class="field right" style="top:6.82in;left:6.55in;width:1.29in;height:0.20in;"><div class="data-right">'.'numero'.'</div></div>'.
'<div class="field date" style="top:6.88in;left:0.61in;width:0.08in;height:0.08in;"><div class="data-left">'.'123'.'</div></div>'.
'<div class="field date" style="top:6.88in;left:1.20in;width:0.08in;height:0.08in;"><div class="data-left">'.'123'.'</div></div>'.
'<div class="field left" style="top:7.06in;left:1.57in;width:4.82in;height:0.24in;"><div class="data-left">'.'Podatak'.'</div></div>'.
'<div class="field right" style="top:7.07in;left:6.55in;width:1.29in;height:0.20in;"><div class="data-right">'.'numero'.'</div></div>'.
'<div class="field date" style="top:7.13in;left:0.61in;width:0.08in;height:0.08in;"><div class="data-left">'.'123'.'</div></div>'.
'<div class="field date" style="top:7.13in;left:1.20in;width:0.08in;height:0.08in;"><div class="data-left">'.'123'.'</div></div>'.
'<div class="field left" style="top:7.31in;left:1.57in;width:4.82in;height:0.24in;"><div class="data-left">'.'Podatak'.'</div></div>'.
'<div class="field right" style="top:7.32in;left:6.55in;width:1.29in;height:0.20in;"><div class="data-right">'.'numero'.'</div></div>'.
'<div class="field date" style="top:7.38in;left:0.61in;width:0.08in;height:0.08in;"><div class="data-left">'.'123'.'</div></div>'.
'<div class="field date" style="top:7.38in;left:1.20in;width:0.08in;height:0.08in;"><div class="data-left">'.'123'.'</div></div>'.
'<div class="field left" style="top:7.56in;left:1.57in;width:4.82in;height:0.24in;"><div class="data-left">'.'Podatak'.'</div></div>'.
'<div class="field right" style="top:7.57in;left:6.55in;width:1.29in;height:0.20in;"><div class="data-right">'.'numero'.'</div></div>'.
'<div class="field date" style="top:7.63in;left:0.61in;width:0.08in;height:0.08in;"><div class="data-left">'.'123'.'</div></div>'.
'<div class="field date" style="top:7.63in;left:1.20in;width:0.08in;height:0.08in;"><div class="data-left">'.'123'.'</div></div>'.
'<div class="field left" style="top:7.81in;left:1.57in;width:4.82in;height:0.24in;"><div class="data-left">'.'Podatak'.'</div></div>'.
'<div class="field right" style="top:7.82in;left:6.55in;width:1.29in;height:0.20in;"><div class="data-right">'.'numero'.'</div></div>'.
'<div class="field date" style="top:7.88in;left:0.61in;width:0.08in;height:0.08in;"><div class="data-left">'.'123'.'</div></div>'.
'<div class="field date" style="top:7.88in;left:1.20in;width:0.08in;height:0.08in;"><div class="data-left">'.'123'.'</div></div>'.
'<div class="field left" style="top:8.06in;left:1.57in;width:4.82in;height:0.24in;"><div class="data-left">'.'Podatak'.'</div></div>'.
'<div class="field right" style="top:8.07in;left:6.55in;width:1.29in;height:0.20in;"><div class="data-right">'.'numero'.'</div></div>'.
'<div class="field date" style="top:8.13in;left:0.61in;width:0.08in;height:0.08in;"><div class="data-left">'.'123'.'</div></div>'.
'<div class="field date" style="top:8.13in;left:1.20in;width:0.08in;height:0.08in;"><div class="data-left">'.'123'.'</div></div>'.
'<div class="field left" style="top:8.31in;left:1.57in;width:4.82in;height:0.24in;"><div class="data-left">'.'Podatak'.'</div></div>'.
'<div class="field right" style="top:8.32in;left:6.55in;width:1.29in;height:0.20in;"><div class="data-right">'.'numero'.'</div></div>'.
'<div class="field date" style="top:8.38in;left:0.61in;width:0.08in;height:0.08in;"><div class="data-left">'.'123'.'</div></div>'.
'<div class="field date" style="top:8.38in;left:1.20in;width:0.08in;height:0.08in;"><div class="data-left">'.'123'.'</div></div>'.
'<div class="field left" style="top:8.56in;left:1.57in;width:4.82in;height:0.24in;"><div class="data-left">'.'Podatak'.'</div></div>'.
'<div class="field right" style="top:8.57in;left:6.55in;width:1.29in;height:0.20in;"><div class="data-right">'.'numero'.'</div></div>'.
'<div class="field date" style="top:8.63in;left:0.61in;width:0.08in;height:0.08in;"><div class="data-left">'.'123'.'</div></div>'.
'<div class="field date" style="top:8.63in;left:1.20in;width:0.08in;height:0.08in;"><div class="data-left">'.'123'.'</div></div>'.
'<div class="field left" style="top:8.81in;left:1.57in;width:4.82in;height:0.24in;"><div class="data-left">'.'Podatak'.'</div></div>'.
'<div class="field right" style="top:8.82in;left:6.55in;width:1.29in;height:0.20in;"><div class="data-right">'.'numero'.'</div></div>'.
'<div class="field date" style="top:8.88in;left:0.61in;width:0.08in;height:0.08in;"><div class="data-left">'.'123'.'</div></div>'.
'<div class="field date" style="top:8.88in;left:1.20in;width:0.08in;height:0.08in;"><div class="data-left">'.'123'.'</div></div>'.
'<div class="field left" style="top:9.06in;left:1.57in;width:4.82in;height:0.24in;"><div class="data-left">'.'Podatak'.'</div></div>'.
'<div class="field right" style="top:9.07in;left:6.55in;width:1.29in;height:0.20in;"><div class="data-right">'.'numero'.'</div></div>'.
'<div class="field date" style="top:9.13in;left:0.61in;width:0.08in;height:0.08in;"><div class="data-left">'.'123'.'</div></div>'.
'<div class="field date" style="top:9.13in;left:1.20in;width:0.08in;height:0.08in;"><div class="data-left">'.'123'.'</div></div>'.
'<div class="field right" style="top:9.42in;left:6.55in;width:1.29in;height:0.20in;"><div class="data-right">'.'numero'.'</div></div>'.
'<div class="field right" style="top:9.92in;left:6.55in;width:1.29in;height:0.20in;"><div class="data-right">'.'numero'.'</div></div>'
,

];

